import { MigrationInterface, QueryRunner } from 'typeorm';

export class initial1670752733502 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "activity_logs" (
            "created_at" date NOT NULL DEFAULT (CURRENT_TIMESTAMP(6)),
            "updated_at" date NOT NULL DEFAULT (CURRENT_TIMESTAMP(6)),
            "deleted_at" date DEFAULT NULL,
            "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
            "user_id" int NOT NULL,
            "description" varchar(255) NOT NULL,
            "ip" varchar(255) DEFAULT NULL
          );
          
          CREATE TABLE "files" (
            "created_at" date NOT NULL DEFAULT (CURRENT_TIMESTAMP(6)),
            "updated_at" date NOT NULL DEFAULT (CURRENT_TIMESTAMP(6)),
            "deleted_at" date DEFAULT NULL,
            "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
            "name" varchar(255) NOT NULL,
            "file_type" int NOT NULL,
            "extension" varchar(255) NOT NULL,
            "description" varchar(255) DEFAULT NULL,
            "path" varchar(255) NOT NULL,
            "user_id" int NOT NULL
          );
          
          CREATE TABLE "forgot_password" (
            "created_at" date NOT NULL DEFAULT (CURRENT_TIMESTAMP(6)),
            "updated_at" date NOT NULL DEFAULT (CURRENT_TIMESTAMP(6)),
            "deleted_at" date DEFAULT NULL,
            "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
            "hash" varchar(255) NOT NULL,
            "user_id" int DEFAULT NULL,
            "forgot_admin" smallint NOT NULL DEFAULT '0'
          );
          
          CREATE TABLE "roles" (
            "created_at" date NOT NULL DEFAULT (CURRENT_TIMESTAMP(6)),
            "updated_at" date NOT NULL DEFAULT (CURRENT_TIMESTAMP(6)),
            "deleted_at" date DEFAULT NULL,
            "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
            "name" varchar(255) NOT NULL,
            "grant_all_access" smallint NOT NULL DEFAULT '0'
          );
          
          CREATE TABLE "user_roles" (
            "created_at" date NOT NULL DEFAULT (CURRENT_TIMESTAMP(6)),
            "updated_at" date NOT NULL DEFAULT (CURRENT_TIMESTAMP(6)),
            "deleted_at" date DEFAULT NULL,
            "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
            "user_id" int NOT NULL,
            "role_id" int NOT NULL
          );
          
          CREATE TABLE "users" (
            "created_at" date NOT NULL DEFAULT (CURRENT_TIMESTAMP(6)),
            "updated_at" date NOT NULL DEFAULT (CURRENT_TIMESTAMP(6)),
            "deleted_at" date DEFAULT NULL,
            "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
            "name" varchar(255) NOT NULL,
            "nik" varchar(255) NOT NULL,
            "email" varchar(255) NOT NULL,
            "password" varchar(255) NOT NULL,
            "provider" varchar(255) NOT NULL DEFAULT 'email',
            "photo" int DEFAULT NULL,
            "status" smallint NOT NULL DEFAULT '1',
            "notification_token" varchar(255) DEFAULT NULL,
            "hash" varchar(255) DEFAULT NULL,
            "employee_position_id" int,
            "phone" varchar(20)
          );
          
          CREATE TABLE "employee_positions" (
            "created_at" date NOT NULL DEFAULT (CURRENT_TIMESTAMP(6)),
            "updated_at" date DEFAULT NULL,
            "deleted_at" date DEFAULT NULL,
            "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
            "name" varchar(255)
          );
          
          CREATE TABLE "oauth_tokens" (
            "created_at" date NOT NULL DEFAULT (CURRENT_TIMESTAMP),
            "updated_at" date DEFAULT NULL,
            "deleted_at" date DEFAULT NULL,
            "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
            "user_id" int NOT NULL,
            "token" varchar(10000) NOT NULL,
            "expired_at" date NOT NULL,
            "revoked" smallint NOT NULL DEFAULT '0'
          );
          
          CREATE TABLE "purchase_orders" (
            "created_at" date NOT NULL DEFAULT (CURRENT_TIMESTAMP),
            "updated_at" date DEFAULT NULL,
            "deleted_at" date DEFAULT NULL,
            "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
            "user_id" int NOT NULL,
            "cc" varchar(255),
            "line_po_status" boolean,
            "line_po_number" varchar(255),
            "po_number" varchar(255),
            "shipment_number" varchar(255),
            "region_id" int,
            "area_id" int,
            "operator_id" int,
            "customer_id" int,
            "project_name" varchar(255),
            "project_code" varchar(255),
            "site_id" int,
            "status" int,
            "item_code" varchar(255),
            "item_description" text,
            "unit_price" int,
            "unit_price_1" int,
            "unit_price_2" int,
            "requested_qty" int,
            "billed_qty" int,
            "due_qty" int,
            "line_amount" int,
            "remaining_from_po" int,
            "unit_id" int,
            "payment_terms_id" int,
            "bidding_area_id" int,
            "publish_date" date,
            "start_date" date,
            "end_date" date,
            "priority_esar_approve" varchar(255),
            "remark_weekly" text,
            "remark_project_id" int,
            "status_of_acceptace_id" int,
            "pending_type_id" int,
            "pending_approval_pd" varchar(255),
            "amount_pending_approval_pd" int,
            "pd_id" int,
            "actual_completion_date" date,
            "ready_invoice" varchar(255),
            "amount_ready_invoice" int,
            "remark_highlight" text
          );
          
          CREATE TABLE "spk" (
            "created_at" date NOT NULL DEFAULT (CURRENT_TIMESTAMP),
            "updated_at" date DEFAULT NULL,
            "deleted_at" date DEFAULT NULL,
            "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
            "spk_number" varchar(255),
            "status" int,
            "region_id" int,
            "transportation_id" int,
            "police_number" varchar(255),
            "cash_advance" int,
            "pay_to_user_id" int,
            "site_id" int,
            "area_id" int,
            "distance" float,
            "work_type" text,
            "po_id" int,
            "distance_to_site_photo" int,
            "remark_inhouse_team" text,
            "km_range_start_photo" int,
            "km_range_end_photo" int,
            "total_range" float,
            "check_in_photo" int,
            "check_out_photo" int,
            "closing_date" date,
            "operation_cost" int,
            "delta_of_settlement" int,
            "cashback" int,
            "cashout" int,
            "remark_admin" text,
            "created_by" int,
            "approved_by" int,
            "approved_over_budget_by" int,
            "paid_by" int,
            "closed_by" int
          );
          
          CREATE TABLE "spk_inhouse_teams" (
            "created_at" date NOT NULL DEFAULT (CURRENT_TIMESTAMP),
            "updated_at" date DEFAULT NULL,
            "deleted_at" date DEFAULT NULL,
            "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
            "spk_id" int,
            "user_id" int
          );
          
          CREATE TABLE "spk_cost_evidences" (
            "created_at" date NOT NULL DEFAULT (CURRENT_TIMESTAMP),
            "updated_at" date DEFAULT NULL,
            "deleted_at" date DEFAULT NULL,
            "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
            "spk_id" int,
            "name" varchar(255),
            "cost" int,
            "photo" int
          );
          
          CREATE TABLE "regions" (
            "created_at" date NOT NULL DEFAULT (CURRENT_TIMESTAMP),
            "updated_at" date DEFAULT NULL,
            "deleted_at" date DEFAULT NULL,
            "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
            "name" varchar(255)
          );
          
          CREATE TABLE "areas" (
            "created_at" date NOT NULL DEFAULT (CURRENT_TIMESTAMP),
            "updated_at" date DEFAULT NULL,
            "deleted_at" date DEFAULT NULL,
            "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
            "name" varchar(255)
          );
          
          CREATE TABLE "operators" (
            "created_at" date NOT NULL DEFAULT (CURRENT_TIMESTAMP),
            "updated_at" date DEFAULT NULL,
            "deleted_at" date DEFAULT NULL,
            "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
            "name" varchar(255)
          );
          
          CREATE TABLE "customers" (
            "created_at" date NOT NULL DEFAULT (CURRENT_TIMESTAMP),
            "updated_at" date DEFAULT NULL,
            "deleted_at" date DEFAULT NULL,
            "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
            "name" varchar(255)
          );
          
          CREATE TABLE "sites" (
            "created_at" date NOT NULL DEFAULT (CURRENT_TIMESTAMP),
            "updated_at" date DEFAULT NULL,
            "deleted_at" date DEFAULT NULL,
            "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
            "name" varchar(255)
          );
          
          CREATE TABLE "units" (
            "created_at" date NOT NULL DEFAULT (CURRENT_TIMESTAMP),
            "updated_at" date DEFAULT NULL,
            "deleted_at" date DEFAULT NULL,
            "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
            "name" varchar(255)
          );
          
          CREATE TABLE "payment_terms" (
            "created_at" date NOT NULL DEFAULT (CURRENT_TIMESTAMP),
            "updated_at" date DEFAULT NULL,
            "deleted_at" date DEFAULT NULL,
            "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
            "name" varchar(255)
          );
          
          CREATE TABLE "bidding_areas" (
            "created_at" date NOT NULL DEFAULT (CURRENT_TIMESTAMP),
            "updated_at" date DEFAULT NULL,
            "deleted_at" date DEFAULT NULL,
            "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
            "name" varchar(255)
          );
          
          CREATE TABLE "remark_projects" (
            "created_at" date NOT NULL DEFAULT (CURRENT_TIMESTAMP),
            "updated_at" date DEFAULT NULL,
            "deleted_at" date DEFAULT NULL,
            "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
            "name" varchar(255)
          );
          
          CREATE TABLE "status_of_acceptaces" (
            "created_at" date NOT NULL DEFAULT (CURRENT_TIMESTAMP),
            "updated_at" date DEFAULT NULL,
            "deleted_at" date DEFAULT NULL,
            "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
            "name" varchar(255)
          );
          
          CREATE TABLE "pending_types" (
            "created_at" date NOT NULL DEFAULT (CURRENT_TIMESTAMP),
            "updated_at" date DEFAULT NULL,
            "deleted_at" date DEFAULT NULL,
            "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
            "name" varchar(255)
          );
          
          CREATE TABLE "pd" (
            "created_at" date NOT NULL DEFAULT (CURRENT_TIMESTAMP),
            "updated_at" date DEFAULT NULL,
            "deleted_at" date DEFAULT NULL,
            "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
            "name" varchar(255)
          );
          
          CREATE TABLE "transportations" (
            "created_at" date NOT NULL DEFAULT (CURRENT_TIMESTAMP),
            "updated_at" date DEFAULT NULL,
            "deleted_at" date DEFAULT NULL,
            "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
            "name" varchar(255)
          );
          
          CREATE INDEX "FK_d54f841fa5478e4734590d44036" ON "activity_logs" ("user_id");
          
          CREATE INDEX "FK_a7435dbb7583938d5e7d1376041" ON "files" ("user_id");
          
          CREATE INDEX "IDX_337214c0b070d18bf6a64955ed" ON "forgot_password" ("hash");
          
          CREATE INDEX "FK_93500e0a028c94b4c54ecaa6351" ON "forgot_password" ("user_id");
          
          CREATE INDEX "FK_87b8888186ca9769c960e926870" ON "user_roles" ("user_id");
          
          CREATE INDEX "FK_b23c65e50a758245a33ee35fda1" ON "user_roles" ("role_id");
          
          CREATE INDEX "IDX_51b8b26ac168fbe7d6f5653e6c" ON "users" ("name");
          
          CREATE INDEX "IDX_3676155292d72c67cd4e090514" ON "users" ("status");
          
          CREATE INDEX "REL_da675fff89ce00f36453c8b242" ON "users" ("photo");
          
          CREATE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email");
          
          CREATE INDEX "IND_oauthToken-user_id" ON "oauth_tokens" ("user_id");
          
          ALTER TABLE "activity_logs" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
          
          ALTER TABLE "files" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
          
          ALTER TABLE "forgot_password" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
          
          ALTER TABLE "user_roles" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
          
          ALTER TABLE "user_roles" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");
          
          ALTER TABLE "users" ADD FOREIGN KEY ("employee_position_id") REFERENCES "employee_positions" ("id");
          
          ALTER TABLE "oauth_tokens" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
          
          ALTER TABLE "purchase_orders" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
          
          ALTER TABLE "purchase_orders" ADD FOREIGN KEY ("area_id") REFERENCES "areas" ("id");
          
          ALTER TABLE "purchase_orders" ADD FOREIGN KEY ("region_id") REFERENCES "regions" ("id");
          
          ALTER TABLE "purchase_orders" ADD FOREIGN KEY ("operator_id") REFERENCES "operators" ("id");
          
          ALTER TABLE "purchase_orders" ADD FOREIGN KEY ("customer_id") REFERENCES "customers" ("id");
          
          ALTER TABLE "purchase_orders" ADD FOREIGN KEY ("site_id") REFERENCES "sites" ("id");
          
          ALTER TABLE "purchase_orders" ADD FOREIGN KEY ("unit_id") REFERENCES "units" ("id");
          
          ALTER TABLE "purchase_orders" ADD FOREIGN KEY ("payment_terms_id") REFERENCES "payment_terms" ("id");
          
          ALTER TABLE "purchase_orders" ADD FOREIGN KEY ("bidding_area_id") REFERENCES "bidding_areas" ("id");
          
          ALTER TABLE "purchase_orders" ADD FOREIGN KEY ("remark_project_id") REFERENCES "remark_projects" ("id");
          
          ALTER TABLE "purchase_orders" ADD FOREIGN KEY ("status_of_acceptace_id") REFERENCES "status_of_acceptaces" ("id");
          
          ALTER TABLE "purchase_orders" ADD FOREIGN KEY ("pending_type_id") REFERENCES "pending_types" ("id");
          
          ALTER TABLE "purchase_orders" ADD FOREIGN KEY ("pd_id") REFERENCES "pd" ("id");
          
          ALTER TABLE "spk" ADD FOREIGN KEY ("region_id") REFERENCES "regions" ("id");
          
          ALTER TABLE "spk" ADD FOREIGN KEY ("transportation_id") REFERENCES "transportations" ("id");
          
          ALTER TABLE "spk" ADD FOREIGN KEY ("pay_to_user_id") REFERENCES "users" ("id");
          
          ALTER TABLE "spk" ADD FOREIGN KEY ("site_id") REFERENCES "sites" ("id");
          
          ALTER TABLE "spk" ADD FOREIGN KEY ("area_id") REFERENCES "areas" ("id");
          
          ALTER TABLE "spk" ADD FOREIGN KEY ("po_id") REFERENCES "purchase_orders" ("id");
          
          ALTER TABLE "spk" ADD FOREIGN KEY ("distance_to_site_photo") REFERENCES "files" ("id");
          
          ALTER TABLE "spk" ADD FOREIGN KEY ("km_range_start_photo") REFERENCES "files" ("id");
          
          ALTER TABLE "spk" ADD FOREIGN KEY ("km_range_end_photo") REFERENCES "files" ("id");
          
          ALTER TABLE "spk" ADD FOREIGN KEY ("check_in_photo") REFERENCES "files" ("id");
          
          ALTER TABLE "spk" ADD FOREIGN KEY ("check_out_photo") REFERENCES "files" ("id");
          
          ALTER TABLE "spk" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id");
          
          ALTER TABLE "spk" ADD FOREIGN KEY ("approved_by") REFERENCES "users" ("id");
          
          ALTER TABLE "spk" ADD FOREIGN KEY ("approved_over_budget_by") REFERENCES "users" ("id");
          
          ALTER TABLE "spk" ADD FOREIGN KEY ("paid_by") REFERENCES "users" ("id");
          
          ALTER TABLE "spk" ADD FOREIGN KEY ("closed_by") REFERENCES "users" ("id");
          
          ALTER TABLE "spk_inhouse_teams" ADD FOREIGN KEY ("spk_id") REFERENCES "spk" ("id");
          
          ALTER TABLE "spk_inhouse_teams" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
          
          ALTER TABLE "spk_cost_evidences" ADD FOREIGN KEY ("photo") REFERENCES "files" ("id");
          `,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
    DROP SCHEMA public CASCADE;
    CREATE SCHEMA public;
    GRANT ALL ON SCHEMA public TO postgres;
    GRANT ALL ON SCHEMA public TO public;
    `);
  }
}
