image: docker:latest
services:
  - docker:dind

stages:
  - build
  - release
  - deploy

variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  # DOCKER_HOST: tcp://docker:2376
  # DOCKER_TLS_CERTDIR: "/certs"
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - cp $ENV_API_DEV .env
    - docker build --pull -t $CONTAINER_RELEASE_IMAGE .
    - docker push $CONTAINER_RELEASE_IMAGE

release-image:
  stage: release
  script:
    - docker tag $CONTAINER_RELEASE_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - main
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE

deploy:
  stage: deploy
  image: kroniak/ssh-client
  before_script:
    - echo "Start deploying to server"
  script:
    - chmod 400 $SSH_API_DEV_PRIVATE_KEY
    - ssh -o StrictHostKeyChecking=no -i $SSH_API_DEV_PRIVATE_KEY root@$IP_DEV "docker pull registry.gitlab.com/playbook-ppkasn/api:latest"
    - ssh -o StrictHostKeyChecking=no -i $SSH_API_DEV_PRIVATE_KEY root@$IP_DEV "docker stop playbook-api || true && docker rm playbook-api || true"
    - ssh -o StrictHostKeyChecking=no -i $SSH_API_DEV_PRIVATE_KEY root@$IP_DEV "docker run --network=api_default -p 3000:3000 -d --name playbook-api registry.gitlab.com/playbook-ppkasn/api:latest"